name: Publish

on:
  push:
    branches:
      - "master"

concurrency: ${{ github.workflow }} - ${{ github.ref }}


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"
      
      - run: pnpm install
      - name: Create Release pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm publish --access=public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
